### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v24-geckos-team-02#1]
**Feature Description**
Create a landing page which is the starting point for most user activity. 

**Major User Stories**
- [ ] As an end user I want to be able to search for books by title and/or author So I can choose the next book I want to read
- [ ] As an end user I want to be able to select from the criteria used in my last n searches as I key into the search fields So I don't have to type or remember search criteria
- [ ] As an end user I want to see books matching the search criteria displayed in an infinite scroll So I can see the book cover thumbnail, title, and author
- [ ] As an end user I want to click on a book to display additional details So I can view additional details to help me decide if I want to read it
- [ ] As an end user I want to mark my favorite books So I can easily find them at a later point in time
- [ ] As an end user I want to display all of my favorite books and organize them in order of their popularity to me So I can easily find the most favored ones

**Additional Considerations**
- The user interface should be consistent across all application components. 
- Performance should not be noticeable to the end user
