### ISSUE TITLE
Setup the Project

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v24-geckos-team-02#8]
**Feature Description**
Setup the project repo with subdirectory structure, initial `readme.md`,  & skeletal application code to display a placeholder landing page. This will be the model team members will follow for the remainder of the project and will allow it to be deployed to an Internet host.

**Major Tasks**
- [X] Create the repo & application skeleton using [Create React App](https://github.com/facebook/create-react-app#creating-an-app) 
- [ ] Replace the CRA generated `readme.md` with on suitable for Bookfinder (see [Keys to a Well Written Readme](https://medium.com/chingu/keys-to-a-well-written-readme-55c53d34fe6d))
- [x] Create a `development` branch
- [X] Choose an Internet Host such as Netlify, Heroku, etc.
- [X] Establish a staging server and setup the `development` branch automatically deploy to it.
- [ ] Establish a production server and setup the `main` branch automatically deploy to it.
- [x] Enable branch protection rules in GitHub to setup `development` as the default branch and to require reviews on all PRs

**Additional Considerations**
Include anything else that may be helpful. For example, links to external resources.

**Comment by ghost** [comment]
I'm setting up CRA as discussed on Discord.
